### ISSUE TITLE
Staying in sync

### ISSUE THREAD

**Issue by ghost** [derhuerst/files-sync-stream#4]
Upon looking into this project, how is it possible to go both direction when

> ...one for sending signaling data and one for sending chunks of data.

?

Maybe I have it confused. It can only handle one file at a time right? That would be the only way I could see this functioning so far.

**Comment by derhuerst** [comment]
> how is it possible to go both direction [...]?

Two `files-sync-stream` peers sync files/blobs in both ways: A gets B's files, and vice-versa.

To do this, each peer has *two* "endpoints", one for exchanging metadata (a.k.a. signaling data) about files/blobs, one for transferring the actual data. This means that you'll have to connect A's signaling endpoint with B's signaling endpoint, and A's data endpoint with B's data endpoint.

I want to improve the readme so that this becomes clear, so you're welcome to make a proposal on how to improve it!

> It can only handle one file at a time right?

It's been a while since I've last looked at that code. It seems like it's only ever transferring 1 file at a time, either A->B or B->A.

This assumes that there's *no performance benefit* in parallelising the transfer, which might of course be the case in some cases.

**Comment by derhuerst** [comment]
Closing this. Please reopen if you still have questions.
